### ISSUE TITLE
[Bug]: Incompatible with Aether

### ISSUE THREAD

**Issue by 48004800** [cominixo/BetterF3#147]
### Describe the Bug

When used together with Aether, the F3 interface will disappear.

https://www.curseforge.com/minecraft/mc-mods/aether/files/4543516

### Steps to Reproduce

Used with Aether, press the F3 button in the game.

### Expected Behavior

The F3 interface did not appear. However, after adjusting the Better F3 Mod settings, the Vanilla F3 interface can appear.

### Modloader Type

Minecraft Forge

### Modloader Version

1.19.4 -45.0.63

### Mod Version

v6.0.1 (1.19.4)

**Comment by bconlon1** [comment]
This appears to be caused by a mixin error of some sort from BetterF3 according to the log when testing this: https://gist.github.com/bconlon1/bd41a9e2bead7cab82be8b756775c943

**Comment by 48004800** [comment]
@cominixo 
Recently, many people have encountered the issue of F3 text disappearing. But they did not provide relatively accurate information. If you have time, you can take a look at my question first. Perhaps it can also solve other people's problems.

**Comment by TreyRuffy** [comment]
I think this was fixed in 6.0.2. Can you test it?

**Comment by 48004800** [comment]
> I think this was fixed in 6.0.2. Can you test it?

The problem has been resolved

**Comment by Vaelzan** [comment]
This is still an issue in Minecraft 1.19.2. It was only fixed for Minecraft 1.19.4 as far as I can see. Same error / stacktrace as in the log shared by bconon1, above.

Relevant issue on The Aether's end: https://github.com/The-Aether-Team/The-Aether/issues/1693
